version: '3'
services:
  app:
    container_name: dashboard
    restart: always
    build: .
    ports:
      - '80:3800'
    links:
      - mongo
    environment:
      - NODE_ENV=production
    ## Mount dashboard front-end on /opt/static
    #volumes:
    #- "../Dashboard/:/opt/static/"
  mongo:
    container_name: mongo
    image: mongo
    #ports:
    #  - "27017:27017"

      
